# Build Stage
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/api/package.json ./apps/api/
COPY packages/database/package.json ./packages/database/
COPY packages/config/package.json ./packages/config/
COPY packages/types/package.json ./packages/types/
COPY packages/utils/package.json ./packages/utils/

# Cài đặt pnpm toàn cục
RUN npm install -g pnpm

# Cài đặt toàn bộ dependencies
RUN pnpm install --frozen-lockfile

COPY . .

# Sinh Prisma Client
RUN npx prisma generate --schema=packages/database/prisma/schema.prisma

# Build các dependencies và api
RUN pnpm --filter @repo/config build
RUN pnpm --filter @repo/types build
RUN pnpm --filter @repo/utils build
RUN pnpm --filter api build

# Production Stage
FROM node:20-alpine AS runner

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/apps/api/package.json ./apps/api/
COPY --from=builder /usr/src/app/apps/api/dist ./apps/api/dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/packages/database/src/index.ts ./packages/database/src/index.ts

ENV NODE_ENV=production
PORT=5000

EXPOSE 5000

CMD ["node", "apps/api/dist/index.js"]
