import React, { useState } from 'react';
import { ArrowRight, Building2, CalendarDays, CheckCircle2, ChevronDown, FileCheck2, MapPin, Phone, Quote, ShieldCheck } from 'lucide-react';
import { Template } from '../../../data/templatesData';

type Props = { template: Template };

const PALETTES = [
  ['#172554', '#d4a853', '#f8f3e9'], ['#334155', '#0ea5e9', '#f8fafc'], ['#075985', '#22c55e', '#eff6ff'], ['#083344', '#f4c76b', '#f0fdfa'],
  ['#1e3a8a', '#38bdf8', '#eff6ff'], ['#14532d', '#f59e0b', '#f0fdf4'], ['#431407', '#fb923c', '#fff7ed'], ['#166534', '#84cc16', '#f7fee7'],
  ['#3f0d1d', '#d4a853', '#fff7ed'], ['#1e40af', '#22d3ee', '#eff6ff'], ['#4c1d95', '#fb7185', '#faf5ff'], ['#0f172a', '#38bdf8', '#f8fafc'],
  ['#7f1d1d', '#fbbf24', '#fef2f2'], ['#365314', '#a3e635', '#f7fee7'], ['#9a3412', '#fdba74', '#fff7ed'], ['#1e293b', '#f97316', '#f8fafc'],
];

const PHOTO_IDS = [
  '1600585154340-be6161a56a0c', '1545324418-cc1a3fa10c00', '1600607687939-ce8a6c25118c',
  '1600566753190-17f0baa2a6c3', '1600047509807-ba8f99d2cdde', '1511818966892-d7d671e672a2',
];

const CONTENT: Record<string, { focus: string; products: string[]; benefits: string[] }> = {
  luxury: { focus: 'Không gian sống riêng tư dành cho chủ nhân tinh tế', products: ['Dinh thự ven hồ', 'Biệt thự sân vườn', 'Penthouse trung tâm'], benefits: ['Tư vấn riêng', 'Hồ sơ chọn lọc', 'Tham quan theo lịch'] },
  minimal: { focus: 'Căn hộ tối ưu công năng và ánh sáng tự nhiên', products: ['Căn hộ một phòng ngủ', 'Căn hộ gia đình', 'Căn hộ sân vườn'], benefits: ['Mặt bằng dễ xem', 'Giá rõ ràng', 'Đặt lịch trực tuyến'] },
  corporate: { focus: 'Nền tảng phân phối dự án cho thị trường Việt Nam', products: ['Dự án đang mở bán', 'Dự án sắp triển khai', 'Dự án đã bàn giao'], benefits: ['Đội ngũ địa phương', 'Quy trình minh bạch', 'Dữ liệu tập trung'] },
  resort: { focus: 'Ngôi nhà thứ hai tại những điểm đến ven biển', products: ['Villa sát biển', 'Căn hộ nghỉ dưỡng', 'Nhà phố du lịch'], benefits: ['Khai thác cho thuê', 'Quản lý vận hành', 'Tiềm năng tăng giá'] },
  apartment: { focus: 'Hệ sinh thái căn hộ dành cho gia đình đô thị', products: ['Căn hộ trung tâm', 'Căn hộ ven sông', 'Căn hộ gần Metro'], benefits: ['So sánh căn', 'Chính sách vay', 'Xem nhà mẫu'] },
  industrial: { focus: 'Hạ tầng sản xuất và kho vận kết nối liên vùng', products: ['Nhà xưởng xây sẵn', 'Kho logistics', 'Đất công nghiệp'], benefits: ['Hồ sơ đầu tư', 'Kết nối cảng', 'Hỗ trợ pháp lý'] },
  villa: { focus: 'Khu biệt thự khép kín cho nhiều thế hệ', products: ['Villa đơn lập', 'Villa song lập', 'Nhà vườn'], benefits: ['An ninh 24/7', 'Cảnh quan riêng', 'Cộng đồng chọn lọc'] },
  eco: { focus: 'Đô thị xanh cân bằng an cư và thiên nhiên', products: ['Nhà phố xanh', 'Căn hộ sinh thái', 'Biệt thự vườn'], benefits: ['Mật độ xanh cao', 'Tiện ích gia đình', 'Vận hành bền vững'] },
  classic: { focus: 'Kiến trúc trường tồn và giá trị truyền đời', products: ['Nhà phố tân cổ điển', 'Dinh thự di sản', 'Biệt thự Indochine'], benefits: ['Thiết kế tinh xảo', 'Vật liệu chọn lọc', 'Giá trị lâu dài'] },
  investment: { focus: 'Phân tích dữ liệu cho quyết định đầu tư hiệu quả', products: ['Tài sản dòng tiền', 'BĐS tăng trưởng', 'Danh mục dài hạn'], benefits: ['Ước tính lợi suất', 'So sánh khu vực', 'Báo cáo định kỳ'] },
  agency: { focus: 'Chiến dịch mở bán tập trung vào chuyển đổi', products: ['Giỏ hàng ưu tiên', 'Căn đẹp mở bán', 'Chính sách giới hạn'], benefits: ['Form nhận giá', 'Đếm ngược', 'Theo dõi nguồn lead'] },
  developer: { focus: 'Năng lực phát triển những đô thị quy mô lớn', products: ['Đại đô thị', 'Khu phức hợp', 'Dự án cộng đồng'], benefits: ['Tiến độ công khai', 'Đối tác uy tín', 'Quản trị bền vững'] },
  project: { focus: 'Quy hoạch rõ ràng cho giá trị đất đai bền vững', products: ['Đất nền có sổ', 'Nhà phố liền kề', 'Shophouse dự án'], benefits: ['Bản đồ phân lô', 'Pháp lý dự án', 'Chọn vị trí'] },
  retail: { focus: 'Mặt bằng thương mại tại khu vực giàu sức mua', products: ['Shophouse đại lộ', 'Khối đế thương mại', 'Phố đi bộ'], benefits: ['Dòng khách ổn định', 'Khai thác linh hoạt', 'Hỗ trợ vận hành'] },
  agent: { focus: 'Chuyên viên địa phương đồng hành cùng khách hàng', products: ['Nhà ở thực', 'Tài sản đầu tư', 'Nhận ký gửi'], benefits: ['Zalo trực tiếp', 'Lịch xem nhanh', 'Tư vấn một-một'] },
};

export default function TemplateExpansionSections({ template }: Props) {
  const [openFaq, setOpenFaq] = useState(0);
  const index = Math.max(0, (template.sortOrder || 1) - 1);
  const number = String(index + 1).padStart(2, '0');
  const [primary, accent, paper] = PALETTES[index % PALETTES.length];
  const copy = CONTENT[template.collectionSlug] || CONTENT.corporate;
  const mode = index % 4;
  const radius = mode === 0 ? '0px' : mode === 1 ? '28px' : mode === 2 ? '12px' : '4px';
  const image = (offset: number, width = 1000) => `https://images.unsplash.com/photo-${PHOTO_IDS[(index + offset) % PHOTO_IDS.length]}?auto=format&fit=crop&w=${width}&q=82`;
  const faqs = ['Thông tin trên website có chỉnh được không?', 'Khách hàng có thể đổi màu sắc và hình ảnh không?', 'Form đăng ký được lưu ở đâu?', 'Bản đồ và thông tin liên hệ thay đổi thế nào?'];

  return <div style={{ background: paper, color: '#172033', ['--template-primary' as string]: primary, ['--template-accent' as string]: accent, ['--template-radius' as string]: radius }}>
    <section className="border-y border-black/10 bg-white py-8"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 px-5 text-center md:grid-cols-4">{[['12+', 'Năm kinh nghiệm'], ['350+', 'Giao dịch hoàn tất'], ['24/7', 'Tiếp nhận yêu cầu'], ['98%', 'Khách hàng hài lòng']].map(([value,label])=><div key={label}><strong className="text-2xl sm:text-3xl" style={{color:primary}}>{value}</strong><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</div></section>

    <section className="py-16 sm:py-24"><div className={`mx-auto grid max-w-7xl items-center gap-10 px-5 ${mode % 2 ? 'lg:grid-cols-[1.15fr_.85fr]' : 'lg:grid-cols-2'}`}><div className={mode === 2 ? 'lg:order-2' : ''}><span className="text-xs font-black tracking-[.18em]" style={{color:primary}}>TỔNG QUAN MẪU BĐS {number}</span><h2 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">{copy.focus}</h2><p className="mt-6 max-w-xl text-sm leading-7 text-slate-600">Nội dung được phát triển riêng cho {template.name}. Khách hàng có thể điều chỉnh tiêu đề, mô tả, ảnh, màu sắc, font chữ và thứ tự hiển thị trong CMS.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{copy.benefits.map(item=><div key={item} className="border-l-4 bg-white p-4 text-sm font-bold" style={{borderColor:accent,borderRadius:radius}}>{item}</div>)}</div></div><img src={image(1,1200)} alt={`Tổng quan ${template.name}`} className={`aspect-[4/3] h-full w-full object-cover ${mode===2?'lg:order-1':''}`} style={{borderRadius:radius}}/></div></section>

    <section className="bg-white py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="text-xs font-black tracking-[.18em]" style={{color:primary}}>BỘ SƯU TẬP NỔI BẬT</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">Sản phẩm dành cho từng nhu cầu</h2></div><button className="inline-flex items-center gap-2 text-sm font-black" style={{color:primary}}>Xem toàn bộ <ArrowRight className="h-4 w-4"/></button></div><div className={`mt-9 grid gap-5 ${mode===0?'md:grid-cols-[1.3fr_.85fr_.85fr]':'md:grid-cols-3'}`}>{copy.products.map((name,i)=><article key={name} className="overflow-hidden border border-slate-200 bg-white" style={{borderRadius:radius}}><img src={image(i+2)} alt={name} className={`w-full object-cover ${mode===0&&i===0?'aspect-[4/3]':'aspect-[16/11]'}`}/><div className="p-5"><span className="text-[10px] font-black tracking-widest" style={{color:accent}}>ĐANG NHẬN QUAN TÂM</span><h3 className="mt-2 text-xl font-black">{name}</h3><p className="mt-3 text-sm text-slate-500">Giá, diện tích và trạng thái được cập nhật trong CMS.</p></div></article>)}</div></div></section>

    <section className="py-16 text-white sm:py-24" style={{background:primary}}><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2"><div><span className="text-xs font-black tracking-[.18em]" style={{color:accent}}>VỊ TRÍ & HẠ TẦNG</span><h2 className="mt-4 text-3xl font-black sm:text-4xl">Kết nối những điểm đến quan trọng</h2><p className="mt-5 text-sm leading-7 text-white/70">Bản đồ minh họa được đặt tại khu vực phù hợp với từng loại dự án. Khách mua mẫu thay địa chỉ và tọa độ Google Maps trực tiếp trong CMS.</p><div className="mt-8 grid grid-cols-2 gap-3">{['Trung tâm hành chính','Trường học','Bệnh viện','Khu mua sắm'].map((x,i)=><div key={x} className="border border-white/15 p-4"><span className="text-xl font-black" style={{color:accent}}>0{i+1}</span><p className="mt-2 text-xs">{x}</p></div>)}</div></div><div className="grid min-h-[380px] place-items-center border border-white/20 bg-white/10" style={{borderRadius:radius}}><div className="text-center"><MapPin className="mx-auto h-12 w-12" style={{color:accent}}/><strong className="mt-4 block">Bản đồ khu vực dự án</strong><p className="mt-2 text-xs text-white/60">TP. Hồ Chí Minh · Hà Nội · Đà Nẵng</p></div></div></div></section>

    <section className="py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5"><div className="text-center"><span className="text-xs font-black tracking-[.18em]" style={{color:primary}}>THƯ VIỆN HÌNH ẢNH</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">Không gian và trải nghiệm thực tế</h2></div><div className={`mt-9 grid gap-3 ${mode===3?'grid-cols-2 md:grid-cols-4':'grid-cols-2 md:grid-cols-3'}`}>{[0,1,2,3,4,5].map((item)=><img key={item} src={image(item,900)} alt={`Thư viện ${item+1}`} className={`${mode===1&&item===0?'col-span-2 row-span-2 aspect-square':'aspect-[4/3]'} h-full w-full object-cover`} style={{borderRadius:radius}}/>)}</div></div></section>

    <section className="bg-white py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5"><span className="text-xs font-black tracking-[.18em]" style={{color:primary}}>PHÁP LÝ & TIẾN ĐỘ</span><h2 className="mt-3 text-3xl font-black">An tâm trong từng bước</h2><div className="mt-9 grid gap-4 md:grid-cols-4">{[['01','Tiếp nhận nhu cầu'],['02','Kiểm tra hồ sơ'],['03','Tham quan thực tế'],['04','Hoàn tất giao dịch']].map(([step,title])=><div key={step} className="border-t-4 bg-slate-50 p-6" style={{borderColor:accent,borderRadius:radius}}><span className="text-3xl font-black" style={{color:primary}}>{step}</span><h3 className="mt-8 font-black">{title}</h3><p className="mt-3 text-xs leading-5 text-slate-500">Quy trình minh bạch, có nhân sự phụ trách và tài liệu đối chiếu.</p></div>)}</div></div></section>

    <section className="py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[.9fr_1.1fr]"><div><Quote className="h-10 w-10" style={{color:accent}}/><h2 className="mt-5 text-3xl font-black">Khách hàng nói về chúng tôi</h2><p className="mt-5 text-sm leading-7 text-slate-600">“Thông tin dễ hiểu, lịch xem linh hoạt và tư vấn đúng nhu cầu của gia đình. Các khoản chi phí được giải thích trước khi đặt cọc.”</p><p className="mt-5 text-xs font-black">NGUYỄN MINH AN · KHÁCH HÀNG TẠI TP.HCM</p></div><div className="grid gap-4 sm:grid-cols-2">{['Tư vấn rõ ràng','Đồng hành tận tâm','Hồ sơ minh bạch','Phản hồi nhanh'].map((x,i)=><div key={x} className="bg-white p-6" style={{borderRadius:radius}}><CheckCircle2 className="h-6 w-6" style={{color:i%2?accent:primary}}/><h3 className="mt-6 font-black">{x}</h3><p className="mt-2 text-xs leading-5 text-slate-500">Trải nghiệm dịch vụ được thiết kế phù hợp khách hàng Việt Nam.</p></div>)}</div></div></section>

    <section className="bg-white py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5"><span className="text-xs font-black tracking-[.18em]" style={{color:primary}}>TIN TỨC & CẨM NANG</span><h2 className="mt-3 text-3xl font-black">Thông tin hữu ích trước khi giao dịch</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{['Cách kiểm tra pháp lý dự án','Kinh nghiệm chọn sản phẩm phù hợp','Cập nhật hạ tầng khu vực'].map((title,i)=><article key={title} className="border border-slate-200" style={{borderRadius:radius}}><img src={image(i+3)} alt={title} className="aspect-[16/9] w-full object-cover"/><div className="p-5"><CalendarDays className="h-5 w-5" style={{color:primary}}/><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-3 text-xs leading-5 text-slate-500">Bài viết có thể tạo, sửa và tối ưu SEO trong CMS.</p></div></article>)}</div></div></section>

    <section className="py-16 sm:py-24"><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-2"><div><span className="text-xs font-black tracking-[.18em]" style={{color:primary}}>CÂU HỎI THƯỜNG GẶP</span><h2 className="mt-3 text-3xl font-black">Thông tin cần biết</h2><p className="mt-5 text-sm leading-7 text-slate-600">Khối FAQ giúp khách tìm hiểu nhanh trước khi liên hệ tư vấn.</p></div><div>{faqs.map((faq,i)=><button key={faq} className="block w-full border-b border-slate-200 py-5 text-left" onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span className="flex items-center justify-between gap-4 font-black">{faq}<ChevronDown className={`h-4 w-4 transition ${openFaq===i?'rotate-180':''}`}/></span>{openFaq===i&&<span className="mt-3 block text-sm leading-6 text-slate-500">Có. Những nội dung khách cần sử dụng đều được cấu hình bằng giao diện CMS, không yêu cầu chỉnh mã nguồn.</span>}</button>)}</div></div></section>

    <section className="px-5 py-16 text-white" style={{background:primary}}><div className="mx-auto grid max-w-6xl items-center gap-8 lg:grid-cols-2"><div><span className="text-xs font-black tracking-[.18em]" style={{color:accent}}>NHẬN BẢNG GIÁ & LỊCH XEM</span><h2 className="mt-3 text-3xl font-black sm:text-4xl">Trao đổi cùng chuyên viên</h2><p className="mt-4 text-sm text-white/70">Dữ liệu form được lưu vào CRM của website.</p><p className="mt-6 flex items-center gap-2 text-sm font-black"><Phone className="h-5 w-5"/> 0909 000 000</p></div><form className="grid gap-3 bg-white p-6 text-slate-800" style={{borderRadius:radius}} onSubmit={e=>e.preventDefault()}><input required className="border p-3 text-sm" placeholder="Họ và tên"/><input required className="border p-3 text-sm" placeholder="Số điện thoại"/><input className="border p-3 text-sm" placeholder="Nhu cầu quan tâm"/><button className="py-3 text-sm font-black text-white" style={{background:accent,color:primary}}>Gửi yêu cầu tư vấn</button></form></div></section>

    <footer className="bg-slate-950 px-5 py-14 text-white"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-4"><div><strong className="text-xl">{template.name}</strong><p className="mt-3 text-xs leading-6 text-white/55">Website demo dành cho thị trường bất động sản Việt Nam.</p></div><div className="text-xs leading-7"><strong>Thông tin liên hệ</strong><p>0909 000 000</p><p>hello@bdsviet.vn</p></div><div className="text-xs leading-7"><strong>Địa chỉ minh họa</strong><p>TP. Hồ Chí Minh, Việt Nam</p><p>Google Maps chỉnh trong CMS</p></div><div className="text-xs leading-7"><strong>Bản quyền</strong><p>© 2026 TEMPLATES BDS.</p><p>Chỉ thay đổi sau khi mua mẫu.</p></div></div></footer>
  </div>;
}
