import fs from 'fs';
import path from 'path';

function findRepoRoot(): string {
  let curr = process.cwd();
  while (curr !== path.dirname(curr)) {
    if (fs.existsSync(path.join(curr, 'pnpm-workspace.yaml'))) {
      return curr;
    }
    curr = path.dirname(curr);
  }
  return process.cwd();
}
const ROOT_DIR = findRepoRoot();
const PORTAL_DATA_PATH = path.join(ROOT_DIR, 'apps/marketplace/src/components/demo/portal-templates/portalData.ts');

const newPortalDataContent = `export interface PortalProperty {
  id: number;
  title: string;
  slug: string;
  price: string;
  priceNum: number; // in billion VND or million VND for rent
  priceUnit: 'tỷ' | 'triệu/tháng' | 'triệu/m²';
  pricePerM2: string;
  area: number; // in m2
  bedrooms: number;
  bathrooms: number;
  direction: 'Đông' | 'Tây' | 'Nam' | 'Bắc' | 'Đông Nam' | 'Đông Bắc' | 'Tây Nam' | 'Tây Bắc';
  legal: 'Sổ hồng riêng' | 'Sổ đỏ chính chủ' | 'HĐMB' | 'Đang chờ sổ' | 'Quy hoạch 1/500';
  furniture: 'Đầy đủ nội thất' | 'Nội thất cơ bản' | 'Nhà thô' | 'Cao cấp nhập khẩu';
  type: 'Căn hộ chung cư' | 'Nhà phố' | 'Biệt thự' | 'Đất nền thổ cư' | 'Văn phòng' | 'Mặt bằng kinh doanh' | 'Kho xưởng';
  category: 'ban' | 'thue' | 'sang-nhuong';
  address: string;
  ward: string;
  district: string;
  city: 'TP. Hồ Chí Minh' | 'Hà Nội' | 'Đà Nẵng' | 'Bình Dương' | 'Đồng Nai' | 'Hải Phòng' | 'Cần Thơ';
  images: string[];
  date: string;
  isHot?: boolean;
  isVerified?: boolean;
  inStock?: boolean;
  featured?: boolean;
  views: number;
  description: string;
  features: string[];
  author: {
    name: string;
    phone: string;
    zalo: string;
    avatar: string;
    role: string;
    verified: boolean;
    rating: number;
    ratingCount: number;
    joinedDate: string;
  };
}

export interface PortalProject {
  id: number;
  title: string;
  slug: string;
  developer: string;
  location: string;
  district: string;
  city: string;
  priceRange: string;
  priceNum: number;
  scale: string;
  status: 'Đang mở bán' | 'Sắp mở bán' | 'Đã bàn giao' | 'Đang xây dựng';
  type: 'Khu phức hợp Căn hộ & Shophouse' | 'Khu đô thị sinh thái' | 'Biệt thự Đảo siêu sang' | 'Tổ hợp Thương mại & Văn phòng';
  thumbnail: string;
  gallery: string[];
  overview: string;
  amenities: { icon: string; title: string; desc: string }[];
  masterplanImg: string;
  units: {
    type: string;
    area: string;
    price: string;
    bedrooms: string;
    bathrooms: string;
    status: string;
  }[];
  handoverDate: string;
  legal: string;
}

export interface PortalNews {
  id: number;
  title: string;
  slug: string;
  category: 'Thị trường BĐS' | 'Pháp lý & Quy hoạch' | 'Phong thủy nhà đất' | 'Cẩm nang mua bán' | 'Kinh nghiệm đầu tư';
  date: string;
  author: string;
  img: string;
  summary: string;
  content: string;
  views: number;
  tags: string[];
}

export interface PortalCity {
  id: number;
  name: string;
  slug: string;
  count: string;
  projectCount: string;
  image: string;
  featuredDistricts: string[];
}

export const PORTAL_CITIES: PortalCity[] = [
  {
    id: 1,
    name: 'TP. Hồ Chí Minh',
    slug: 'tp-ho-chi-minh',
    count: '24,580 tin đăng',
    projectCount: '142 dự án',
    image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=800&q=80',
    featuredDistricts: ['Quận 1', 'Quận 2 (TP. Thủ Đức)', 'Quận 7', 'Bình Thạnh', 'Thủ Đức'],
  },
  {
    id: 2,
    name: 'Hà Nội',
    slug: 'ha-noi',
    count: '18,920 tin đăng',
    projectCount: '98 dự án',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    featuredDistricts: ['Tây Hồ', 'Cầu Giấy', 'Hoàn Kiếm', 'Nam Từ Liêm', 'Thanh Xuân', 'Long Biên'],
  },
  {
    id: 3,
    name: 'Đà Nẵng',
    slug: 'da-nang',
    count: '8,450 tin đăng',
    projectCount: '45 dự án',
    image: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=800&q=80',
    featuredDistricts: ['Hải Châu', 'Sơn Trà', 'Ngũ Hành Sơn', 'Cẩm Lệ', 'Liên Chiểu'],
  },
  {
    id: 4,
    name: 'Bình Dương',
    slug: 'binh-duong',
    count: '7,320 tin đăng',
    projectCount: '36 dự án',
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    featuredDistricts: ['TP. Thủ Dầu Một', 'TP. Dĩ An', 'TP. Thuận An', 'Bến Cát', 'Tân Uyên'],
  },
  {
    id: 5,
    name: 'Đồng Nai',
    slug: 'dong-nai',
    count: '5,120 tin đăng',
    projectCount: '28 dự án',
    image: 'https://images.unsplash.com/photo-1519999482648-25049ddd37b1?auto=format&fit=crop&w=800&q=80',
    featuredDistricts: ['TP. Biên Hòa', 'Long Thành', 'Nhơn Trạch', 'Trảng Bom'],
  },
  {
    id: 6,
    name: 'Hải Phòng',
    slug: 'hai-phong',
    count: '4,200 tin đăng',
    projectCount: '22 dự án',
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    featuredDistricts: ['Lê Chân', 'Hồng Bàng', 'Ngô Quyền', 'Thủy Nguyên', 'Dương Kinh'],
  },
];

export const PORTAL_PROPERTIES: PortalProperty[] = [
  // ── 12 BẤT ĐỘNG SẢN BÁN (CATEGORY = 'ban') ──────────────────────────────────
  {
    id: 101,
    title: 'Bán gấp căn hộ 2PN Grand Marina Saigon view trực diện sông Sài Gòn & cầu Ba Son',
    slug: 'can-ho-2pn-grand-marina-saigon-view-song-sai-gon',
    price: '18.5 Tỷ',
    priceNum: 18.5,
    priceUnit: 'tỷ',
    pricePerM2: '210 tr/m²',
    area: 88,
    bedrooms: 2,
    bathrooms: 2,
    direction: 'Đông Nam',
    legal: 'Sổ hồng riêng',
    furniture: 'Cao cấp nhập khẩu',
    type: 'Căn hộ chung cư',
    category: 'ban',
    address: 'Số 2 Tôn Đức Thắng, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    ward: 'Phường Bến Nghé',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm nay',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 1840,
    description: 'Cần bán gấp căn hộ hạng sang Grand Marina Saigon, dự án chuẩn Marriott Quốc tế đầu tiên tại trung tâm Quận 1. Tầng trung view trực diện sông Sài Gòn và Landmark 81 cực thoáng mát.',
    features: ['Hồ bơi vô cực', 'View sông Sài Gòn', 'Bến du thuyền', 'Ga Metro Ba Son', 'Smart Home cao cấp', 'An ninh 24/7'],
    author: {
      name: 'Nguyễn Văn Minh',
      phone: '0908 123 456',
      zalo: '0908123456',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên viên BĐS Cao Cấp Quận 1',
      verified: true,
      rating: 4.9,
      ratingCount: 58,
      joinedDate: 'Thành viên 4 năm',
    },
  },
  {
    id: 102,
    title: 'Bán biệt thự song lập Vinhomes Riverside Long Biên, đường Hoa Phượng, có hồ cá Koi',
    slug: 'ban-biet-thu-vinhomes-riverside-long-bien-ha-noi',
    price: '48.5 Tỷ',
    priceNum: 48.5,
    priceUnit: 'tỷ',
    pricePerM2: '215 tr/m²',
    area: 225,
    bedrooms: 4,
    bathrooms: 5,
    direction: 'Đông Nam',
    legal: 'Sổ đỏ chính chủ',
    furniture: 'Đầy đủ nội thất',
    type: 'Biệt thự',
    category: 'ban',
    address: 'Đường Hoa Phượng, KĐT Vinhomes Riverside, Phường Phúc Lợi, Long Biên, Hà Nội',
    ward: 'Phúc Lợi',
    district: 'Long Biên',
    city: 'Hà Nội',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm nay',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 2450,
    description: 'Bán biệt thự Vinhomes Riverside hướng sông sinh thái, hoàn thiện nội thất gỗ óc chó cao cấp. Sân vườn rộng rãi có hồ cá Koi và chòi vọng cảnh bên sông.',
    features: ['Sông sinh thái sau nhà', 'Hồ cá Koi', 'Nội thất gỗ óc chó', 'An ninh 4 lớp', 'Sổ đỏ sẵn sàng'],
    author: {
      name: 'Phạm Hoàng Anh',
      phone: '0912 345 678',
      zalo: '0912345678',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên gia Biệt Thự Vinhomes Riverside',
      verified: true,
      rating: 5.0,
      ratingCount: 72,
      joinedDate: 'Thành viên 5 năm',
    },
  },
  {
    id: 103,
    title: 'Bán căn hộ Duplex Heritage West Lake Tây Hồ view trọn Hồ Tây lộng gió',
    slug: 'ban-can-ho-duplex-heritage-west-lake-tay-ho-ha-noi',
    price: '28.0 Tỷ',
    priceNum: 28.0,
    priceUnit: 'tỷ',
    pricePerM2: '160 tr/m²',
    area: 175,
    bedrooms: 3,
    bathrooms: 4,
    direction: 'Tây Bắc',
    legal: 'Sổ hồng riêng',
    furniture: 'Cao cấp nhập khẩu',
    type: 'Căn hộ chung cư',
    category: 'ban',
    address: '677 Lạc Long Quân, Phường Phú Thượng, Quận Tây Hồ, Hà Nội',
    ward: 'Phú Thượng',
    district: 'Tây Hồ',
    city: 'Hà Nội',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm nay',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 3120,
    description: 'Chính chủ chuyển nhượng căn Duplex Heritage West Lake view trực diện Hồ Tây vĩnh viễn. Thang máy riêng tận cửa, bể bơi vô cực nước nóng trên cao.',
    features: ['View toàn cảnh Hồ Tây', 'Thang máy riêng', 'Bể bơi nước nóng', 'Sảnh đón 6 sao', 'Chủ đầu tư CapitaLand'],
    author: {
      name: 'Vũ Thị Minh Hằng',
      phone: '0977 112 233',
      zalo: '0977112233',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
      role: 'Đại sứ BĐS Tây Hồ',
      verified: true,
      rating: 4.9,
      ratingCount: 65,
      joinedDate: 'Thành viên 3 năm',
    },
  },
  {
    id: 104,
    title: 'Bán nhà phố mặt tiền đường Nguyễn Văn Linh Quận 7, tiện kinh doanh đa ngành nghề',
    slug: 'nha-pho-mat-tien-nguyen-van-linh-quan-7',
    price: '26.8 Tỷ',
    priceNum: 26.8,
    priceUnit: 'tỷ',
    pricePerM2: '178 tr/m²',
    area: 150,
    bedrooms: 5,
    bathrooms: 6,
    direction: 'Nam',
    legal: 'Sổ hồng riêng',
    furniture: 'Đầy đủ nội thất',
    type: 'Nhà phố',
    category: 'ban',
    address: 'Đường Nguyễn Văn Linh, Phường Tân Phong, Quận 7, TP. Hồ Chí Minh',
    ward: 'Phường Tân Phong',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm qua',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 1250,
    description: 'Chính chủ xuất cảnh bán gấp nhà phố mặt tiền trục Nguyễn Văn Linh, Phú Mỹ Hưng, Quận 7. Xây 1 trệt 4 lầu + thang máy, đang cho thuê 65 triệu/tháng.',
    features: ['Thang máy cao cấp', 'Mặt tiền đường lớn', 'Vỉa hè 8m', 'Đang cho thuê 65tr/tháng', 'Sổ hồng hoàn công'],
    author: {
      name: 'Trần Thị Thu Thảo',
      phone: '0919 888 777',
      zalo: '0919888777',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
      role: 'Trưởng phòng Kinh Doanh Phú Mỹ Hưng',
      verified: true,
      rating: 5.0,
      ratingCount: 84,
      joinedDate: 'Thành viên 6 năm',
    },
  },
  {
    id: 105,
    title: 'Bán biệt thự biển Sun Premier Village Mũi Ông Đội Phú Quốc, cam kết dòng tiền 12%/năm',
    slug: 'ban-biet-thu-bien-sun-premier-village-phu-quoc',
    price: '38.0 Tỷ',
    priceNum: 38.0,
    priceUnit: 'tỷ',
    pricePerM2: '95 tr/m²',
    area: 400,
    bedrooms: 3,
    bathrooms: 4,
    direction: 'Đông',
    legal: 'Sổ hồng riêng',
    furniture: 'Cao cấp nhập khẩu',
    type: 'Biệt thự',
    category: 'ban',
    address: 'Mũi Ông Đội, Phường An Thới, TP. Phú Quốc, Kiên Giang',
    ward: 'An Thới',
    district: 'Phú Quốc',
    city: 'TP. Hồ Chí Minh',
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
    ],
    date: '2 ngày trước',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: false,
    views: 1980,
    description: 'Biệt thự sát biển 2 mặt biển độc nhất Phú Quốc, vừa ngắm bình minh vừa ngắm hoàng hôn. Đang vận hành bởi Accor Hotels chia sẻ doanh thu 85/15.',
    features: ['Sát biển riêng tư', 'Bể bơi vô cực', 'Vận hành bởi Accor', 'Tặng 15 đêm VIP/năm', 'Sổ hồng lâu dài'],
    author: {
      name: 'Lê Minh Tuấn',
      phone: '0938 555 666',
      zalo: '0938555666',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên gia BĐS Nghỉ Dưỡng',
      verified: true,
      rating: 4.8,
      ratingCount: 39,
      joinedDate: 'Thành viên 2 năm',
    },
  },
  {
    id: 106,
    title: 'Bán đất nền phân lô mặt tiền ĐT 743 Thuận An Bình Dương, sổ đỏ thổ cư 100%',
    slug: 'ban-dat-nen-thuan-an-binh-duong-so-do-tho-cu',
    price: '3.85 Tỷ',
    priceNum: 3.85,
    priceUnit: 'tỷ',
    pricePerM2: '38.5 tr/m²',
    area: 100,
    bedrooms: 0,
    bathrooms: 0,
    direction: 'Đông Bắc',
    legal: 'Sổ đỏ chính chủ',
    furniture: 'Nhà thô',
    type: 'Đất nền thổ cư',
    category: 'ban',
    address: 'Mặt tiền đường ĐT 743, Phường An Phú, TP. Thuận An, Bình Dương',
    ward: 'An Phú',
    district: 'TP. Thuận An',
    city: 'Bình Dương',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    date: '3 ngày trước',
    isHot: false,
    isVerified: true,
    inStock: true,
    featured: false,
    views: 890,
    description: 'Đất nền phân lô vuông vắn 5x20m, mặt tiền đường nhựa 16m có vỉa hè cây xanh, đối diện KCN VSIP 1, thuận tiện xây trọ hoặc kinh doanh buôn bán.',
    features: ['Thổ cư 100%', 'Mặt tiền 16m', 'Đối diện KCN VSIP 1', 'Xây dựng tự do', 'Sổ đỏ công chứng ngay'],
    author: {
      name: 'Hoàng Quốc Việt',
      phone: '0988 223 344',
      zalo: '0988223344',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
      role: 'Môi Giới Đất Nền Bình Dương',
      verified: true,
      rating: 4.7,
      ratingCount: 31,
      joinedDate: 'Thành viên 3 năm',
    },
  },

  // ── 12 BẤT ĐỘNG SẢN CHO THUÊ (CATEGORY = 'thue') ───────────────────────────
  {
    id: 201,
    title: 'Cho thuê căn hộ cao cấp 3PN Vinhomes Metropolis Liễu Giai Ba Đình full nội thất Ý',
    slug: 'cho-thue-can-ho-vinhomes-metropolis-lieu-giai-ha-noi',
    price: '38 Triệu/tháng',
    priceNum: 38,
    priceUnit: 'triệu/tháng',
    pricePerM2: '320k/m²',
    area: 120,
    bedrooms: 3,
    bathrooms: 2,
    direction: 'Đông Nam',
    legal: 'Sổ hồng riêng',
    furniture: 'Cao cấp nhập khẩu',
    type: 'Căn hộ chung cư',
    category: 'thue',
    address: '29 Liễu Giai, Phường Ngọc Khánh, Quận Ba Đình, Hà Nội',
    ward: 'Ngọc Khánh',
    district: 'Ba Đình',
    city: 'Hà Nội',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm nay',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 1560,
    description: 'Cho thuê căn hộ 3 phòng ngủ Vinhomes Metropolis tầng 28 view trọn vẹn 4 hồ trung tâm Hà Nội. Đầy đủ nội thất nhập khẩu Ý, phù hợp chuyên gia nước ngoài và đại sứ quán.',
    features: ['View 4 hồ Hà Nội', 'Nội thất nhập khẩu Ý', 'Trung tâm Ba Đình', 'Bể bơi tầng mái', 'Lễ tân 24/7'],
    author: {
      name: 'Vũ Thị Minh Hằng',
      phone: '0977 112 233',
      zalo: '0977112233',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên viên Cho Thuê Hà Nội VIP',
      verified: true,
      rating: 5.0,
      ratingCount: 52,
      joinedDate: 'Thành viên 4 năm',
    },
  },
  {
    id: 202,
    title: 'Cho thuê biệt thự sân vườn view Hồ Tây Quảng An, có hồ bơi riêng cho chuyên gia',
    slug: 'cho-thue-biet-thu-ho-tay-quang-an-ha-noi',
    price: '95 Triệu/tháng',
    priceNum: 95,
    priceUnit: 'triệu/tháng',
    pricePerM2: '270k/m²',
    area: 350,
    bedrooms: 5,
    bathrooms: 6,
    direction: 'Tây Nam',
    legal: 'Sổ đỏ chính chủ',
    furniture: 'Đầy đủ nội thất',
    type: 'Biệt thự',
    category: 'thue',
    address: 'Đường Đặng Thai Mai, Phường Quảng An, Quận Tây Hồ, Hà Nội',
    ward: 'Quảng An',
    district: 'Tây Hồ',
    city: 'Hà Nội',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm nay',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 2180,
    description: 'Biệt thự kiểu Pháp cổ điển cách mặt nước Hồ Tây 50m, sân vườn rợp bóng cây xanh, bể bơi ngoài trời riêng biệt. Đã từng cho đại sứ các nước châu Âu thuê lâu dài.',
    features: ['Cách Hồ Tây 50m', 'Hồ bơi riêng', 'Sân vườn 150m²', 'Nội thất gỗ tự nhiên', 'An ninh tuyệt đối'],
    author: {
      name: 'Phạm Hoàng Anh',
      phone: '0912 345 678',
      zalo: '0912345678',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên gia Biệt Thự Tây Hồ',
      verified: true,
      rating: 5.0,
      ratingCount: 72,
      joinedDate: 'Thành viên 5 năm',
    },
  },
  {
    id: 203,
    title: 'Cho thuê căn hộ 3PN Landmark 81 Vinhomes Central Park nội thất sang trọng tầng cao',
    slug: 'cho-thue-can-ho-3pn-landmark-81-vinhomes-central-park',
    price: '45 Triệu/tháng',
    priceNum: 45,
    priceUnit: 'triệu/tháng',
    pricePerM2: '410k/m²',
    area: 110,
    bedrooms: 3,
    bathrooms: 2,
    direction: 'Đông Bắc',
    legal: 'Sổ hồng riêng',
    furniture: 'Cao cấp nhập khẩu',
    type: 'Căn hộ chung cư',
    category: 'thue',
    address: 'Tòa Landmark 81, 720A Điện Biên Phủ, Phường 22, Quận Bình Thạnh, TP. Hồ Chí Minh',
    ward: 'Phường 22',
    district: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm nay',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 2890,
    description: 'Căn hộ tầng 42 tòa nhà cao nhất Việt Nam Landmark 81, tầm nhìn bao quát toàn bộ công viên 14ha và sông Sài Gòn. Đầy đủ tiện nghi chỉ xách vali vào ở.',
    features: ['Tầng 42 Landmark 81', 'View sông Sài Gòn', 'Công viên ven sông 14ha', 'Thang máy thẻ từ VIP', 'Hồ bơi vô cực'],
    author: {
      name: 'Nguyễn Văn Minh',
      phone: '0908 123 456',
      zalo: '0908123456',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên viên Cho Thuê Vinhomes',
      verified: true,
      rating: 4.9,
      ratingCount: 58,
      joinedDate: 'Thành viên 4 năm',
    },
  },
  {
    id: 204,
    title: 'Cho thuê văn phòng hạng A tòa nhà Bitexco Financial Tower Quận 1 diện tích 250m²',
    slug: 'cho-thue-van-phong-bitexco-financial-tower-quan-1',
    price: '185 Triệu/tháng',
    priceNum: 185,
    priceUnit: 'triệu/tháng',
    pricePerM2: '740k/m²',
    area: 250,
    bedrooms: 0,
    bathrooms: 4,
    direction: 'Đông Nam',
    legal: 'HĐMB',
    furniture: 'Đầy đủ nội thất',
    type: 'Văn phòng',
    category: 'thue',
    address: 'Số 2 Hải Triều, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    ward: 'Bến Nghé',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm qua',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: false,
    views: 1420,
    description: 'Cho thuê sàn văn phòng hạng A tại tháp tài chính Bitexco Quận 1. Đã ngăn phòng kính giám đốc, phòng họp lớn 20 người và khu làm việc mở cho 40 nhân viên.',
    features: ['Văn phòng hạng A', 'Sàn nâng cao cấp', 'Điều hòa trung tâm Chiller', 'Máy phát điện 100%', 'PCCC chuẩn quốc tế'],
    author: {
      name: 'Trần Thị Thu Thảo',
      phone: '0919 888 777',
      zalo: '0919888777',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
      role: 'Quản Lý BĐS Thương Mại',
      verified: true,
      rating: 5.0,
      ratingCount: 84,
      joinedDate: 'Thành viên 6 năm',
    },
  },
  {
    id: 205,
    title: 'Cho thuê nhà nguyên căn 4 tầng đường Trần Duy Hưng Cầu Giấy làm văn phòng / spa',
    slug: 'cho-thue-nha-nguyen-can-tran-duy-hung-cau-giay-ha-noi',
    price: '55 Triệu/tháng',
    priceNum: 55,
    priceUnit: 'triệu/tháng',
    pricePerM2: '550k/m²',
    area: 100,
    bedrooms: 6,
    bathrooms: 5,
    direction: 'Nam',
    legal: 'Sổ đỏ chính chủ',
    furniture: 'Nội thất cơ bản',
    type: 'Nhà phố',
    category: 'thue',
    address: 'Đường Trần Duy Hưng, Phường Trung Hòa, Quận Cầu Giấy, Hà Nội',
    ward: 'Trung Hòa',
    district: 'Cầu Giấy',
    city: 'Hà Nội',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    ],
    date: '2 ngày trước',
    isHot: false,
    isVerified: true,
    inStock: true,
    featured: false,
    views: 1100,
    description: 'Nhà phân lô ngõ ô tô tránh nhau Trần Duy Hưng, diện tích 100m² x 4 tầng, mặt tiền 6m. Phù hợp làm thẩm mỹ viện, trung tâm ngoại ngữ hoặc trụ sở công ty.',
    features: ['Mặt tiền 6m', 'Ô tô đỗ cửa', 'Vị trí sầm uất Cầu Giấy', 'Hợp đồng dài hạn', 'Giá thuê ổn định'],
    author: {
      name: 'Vũ Thị Minh Hằng',
      phone: '0977 112 233',
      zalo: '0977112233',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên viên Cho Thuê Hà Nội VIP',
      verified: true,
      rating: 4.9,
      ratingCount: 65,
      joinedDate: 'Thành viên 3 năm',
    },
  },
  {
    id: 206,
    title: 'Cho thuê kho xưởng xây sẵn KCN VSIP 1 Thuận An Bình Dương diện tích 2.500m²',
    slug: 'cho-thue-kho-xuong-kcn-vsip-1-thuan-an-binh-duong',
    price: '160 Triệu/tháng',
    priceNum: 160,
    priceUnit: 'triệu/tháng',
    pricePerM2: '64k/m²',
    area: 2500,
    bedrooms: 0,
    bathrooms: 6,
    direction: 'Bắc',
    legal: 'Quy hoạch 1/500',
    furniture: 'Nhà thô',
    type: 'Kho xưởng',
    category: 'thue',
    address: 'Đường Số 8, KCN VSIP 1, Phường An Phú, TP. Thuận An, Bình Dương',
    ward: 'An Phú',
    district: 'TP. Thuận An',
    city: 'Bình Dương',
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=1200&q=80',
    ],
    date: '3 ngày trước',
    isHot: false,
    isVerified: true,
    inStock: true,
    featured: false,
    views: 760,
    description: 'Kho xưởng tiêu chuẩn công nghiệp cao, trần cao 11m, sàn chịu lực 5 tấn/m², trạm điện 560kVA riêng biệt, hệ thống PCCC tự động Sprinkler nghiệm thu đầy đủ.',
    features: ['Trạm điện 560kVA', 'PCCC tự động Sprinkler', 'Sàn chịu lực 5 tấn/m²', 'Xe Container 40ft vào tận nơi', 'Pháp lý FDI'],
    author: {
      name: 'Hoàng Quốc Việt',
      phone: '0988 223 344',
      zalo: '0988223344',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên gia BĐS Công Nghiệp',
      verified: true,
      rating: 4.7,
      ratingCount: 31,
      joinedDate: 'Thành viên 3 năm',
    },
  },

  // ── 12 BẤT ĐỘNG SẢN SANG NHƯỢNG (CATEGORY = 'sang-nhuong') ──────────────────
  {
    id: 301,
    title: 'Sang nhượng quán cafe acoustic 2 mặt tiền phố cổ Hàng Buồm Hoàn Kiếm doanh thu tốt',
    slug: 'sang-nhuong-quan-cafe-hang-buom-hoan-kiem-ha-noi',
    price: '450 Triệu',
    priceNum: 0.45,
    priceUnit: 'tỷ',
    pricePerM2: '5.6 tr/m²',
    area: 80,
    bedrooms: 0,
    bathrooms: 2,
    direction: 'Đông Nam',
    legal: 'Sổ đỏ chính chủ',
    furniture: 'Đầy đủ nội thất',
    type: 'Mặt bằng kinh doanh',
    category: 'sang-nhuong',
    address: 'Phố Hàng Buồm, Phường Hàng Buồm, Quận Hoàn Kiếm, Hà Nội',
    ward: 'Hàng Buồm',
    district: 'Hoàn Kiếm',
    city: 'Hà Nội',
    images: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm nay',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 3200,
    description: 'Do chuyển vào TP.HCM sinh sống cần sang nhượng gấp quán cafe phong cách vintage phố cổ đang kinh doanh rất đông khách du lịch Tây và giới trẻ. Đầy đủ máy pha cà phê La Marzocco, âm thanh Bose.',
    features: ['Vị trí phố đi bộ Hoàn Kiếm', 'Máy pha La Marzocco', 'Lượng khách quen ổn định', 'Hợp đồng thuê 5 năm', 'Doanh thu 120tr/tháng'],
    author: {
      name: 'Vũ Thị Minh Hằng',
      phone: '0977 112 233',
      zalo: '0977112233',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên viên Sang Nhượng Hà Nội',
      verified: true,
      rating: 4.9,
      ratingCount: 65,
      joinedDate: 'Thành viên 3 năm',
    },
  },
  {
    id: 302,
    title: 'Sang nhượng chuỗi nhà hàng Nhật Bản BBQ lẩu nướng tại Phan Xích Long Phú Nhuận',
    slug: 'sang-nhuong-nha-hang-nhat-ban-phan-xich-long-phu-nhuan',
    price: '1.2 Tỷ',
    priceNum: 1.2,
    priceUnit: 'tỷ',
    pricePerM2: '4.8 tr/m²',
    area: 250,
    bedrooms: 0,
    bathrooms: 4,
    direction: 'Đông',
    legal: 'Sổ hồng riêng',
    furniture: 'Đầy đủ nội thất',
    type: 'Mặt bằng kinh doanh',
    category: 'sang-nhuong',
    address: 'Đường Phan Xích Long, Phường 2, Quận Phú Nhuận, TP. Hồ Chí Minh',
    ward: 'Phường 2',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    images: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm nay',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: true,
    views: 2980,
    description: 'Sang nhượng toàn bộ trang thiết bị nhà hàng nướng không khói Nhật Bản cao cấp trục phố ẩm thực Phan Xích Long. Gồm 22 bàn nướng hút âm, hệ thống bếp công nghiệp Inox 304 và kho đông lạnh.',
    features: ['Trục phố ẩm thực số 1', 'Hệ thống hút khói âm bàn', 'Bếp Inox 304 chuẩn Nhật', 'Lợi nhuận ròng 80tr/tháng', 'Chuyển giao công thức'],
    author: {
      name: 'Trần Thị Thu Thảo',
      phone: '0919 888 777',
      zalo: '0919888777',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
      role: 'Quản Lý BĐS Thương Mại',
      verified: true,
      rating: 5.0,
      ratingCount: 84,
      joinedDate: 'Thành viên 6 năm',
    },
  },
  {
    id: 303,
    title: 'Sang nhượng Shophouse khối đế chung cư cao cấp Thảo Điền Quận 2 đang làm Mini Mart',
    slug: 'sang-nhuong-shophouse-thao-dien-quan-2',
    price: '680 Triệu',
    priceNum: 0.68,
    priceUnit: 'tỷ',
    pricePerM2: '6.8 tr/m²',
    area: 100,
    bedrooms: 0,
    bathrooms: 2,
    direction: 'Nam',
    legal: 'HĐMB',
    furniture: 'Đầy đủ nội thất',
    type: 'Mặt bằng kinh doanh',
    category: 'sang-nhuong',
    address: 'Đường Xa Lộ Hà Nội, Phường Thảo Điền, Quận 2, TP. Hồ Chí Minh',
    ward: 'Thảo Điền',
    district: 'Quận 2 (TP. Thủ Đức)',
    city: 'TP. Hồ Chí Minh',
    images: [
      'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    ],
    date: 'Hôm qua',
    isHot: true,
    isVerified: true,
    inStock: true,
    featured: false,
    views: 1850,
    description: 'Cửa hàng tiện lợi phục vụ trực tiếp cho 1.200 hộ cư dân toà nhà Thảo Điền Pearl. Doanh thu bán hàng ổn định, giá thuê mặt bằng cực mềm.',
    features: ['1200 căn hộ nội khu', 'Kệ siêu thị cao cấp', 'Hệ thống POS quét mã', 'Tủ mát tủ đông Sanaky', 'Hợp đồng thuê còn 4 năm'],
    author: {
      name: 'Nguyễn Văn Minh',
      phone: '0908 123 456',
      zalo: '0908123456',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
      role: 'Chuyên viên BĐS Cao Cấp Quận 1',
      verified: true,
      rating: 4.9,
      ratingCount: 58,
      joinedDate: 'Thành viên 4 năm',
    },
  },
  {
    id: 304,
    title: 'Sang nhượng tiệm Spa & Clinic thẩm mỹ 5 tầng mặt phố Tô Hiến Thành Hai Bà Trưng Hà Nội',
    slug: 'sang-nhuong-spa-tham-my-hai-ba-trung-ha-noi',
    price: '850 Triệu',
    priceNum: 0.85,
    priceUnit: 'tỷ',
    pricePerM2: '4.25 tr/m²',
    area: 200,
    bedrooms: 0,
    bathrooms: 5,
    direction: 'Tây Nam',
    legal: 'Sổ đỏ chính chủ',
    furniture: 'Cao cấp nhập khẩu',
    type: 'Mặt bằng kinh doanh',
    category: 'sang-nhuong',
    address: 'Phố Tô Hiến Thành, Phường Lê Đại Hành, Quận Hai Bà Trưng, Hà Nội',
    ward: 'Lê Đại Hành',
    district: 'Hoàn Kiếm',
    city: 'Hà Nội',
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1200&q=80',
    ],
    date: '2 ngày trước',
    isHot: false,
    isVerified: true,
    inStock: true,
    featured: false,
    views: 1450,
    description: 'Chuyển nhượng toàn bộ trang thiết bị máy laser CO2 Fractional, máy triệt lông Diode Laser, 12 giường spa cao cấp và tập khách hàng hơn 3.000 thành viên VIP.',
    features: ['Dữ liệu 3000 khách VIP', 'Máy móc thẩm mỹ công nghệ cao', 'Mặt phố trung tâm Hai Bà Trưng', 'Phòng xông hơi đá muối', 'Giấy phép hoạt động đầy đủ'],
    author: {
      name: 'Vũ Thị Minh Hằng',
      phone: '0977 112 233',
      zalo: '0977112233',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
      role: 'Đại sứ BĐS Hà Nội',
      verified: true,
      rating: 4.9,
      ratingCount: 65,
      joinedDate: 'Thành viên 3 năm',
    },
  },
];

export const PORTAL_PROJECTS: PortalProject[] = [
  {
    id: 201,
    title: 'The Global City Thủ Đức',
    slug: 'the-global-city-thu-duc',
    developer: 'Masterise Homes',
    location: 'Đường Đỗ Xuân Hợp, Phường An Phú, TP. Thủ Đức, TP.HCM',
    district: 'Quận 2 (TP. Thủ Đức)',
    city: 'TP. Hồ Chí Minh',
    priceRange: 'Từ 350 - 450 triệu/m²',
    priceNum: 350,
    scale: '117.4 ha - Khu đô thị phức hợp chuẩn quốc tế do Foster + Partners thiết kế',
    status: 'Đang mở bán',
    type: 'Khu phức hợp Căn hộ & Shophouse',
    thumbnail: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    ],
    overview: 'The Global City là đại đô thị biểu tượng mới của toàn Đông Nam Á, tích hợp kênh đào nhạc nước lớn nhất khu vực, TTTM 123.000m² và phân khu nhà phố thương mại Soho sang trọng.',
    amenities: [
      { icon: 'Music', title: 'Kênh Đào Nhạc Nước', desc: 'Quy mô dài 2km lớn nhất Đông Nam Á biểu diễn hàng tuần' },
      { icon: 'ShoppingBag', title: 'TTTM Hạng A 123.000m²', desc: 'Nơi quy tụ hơn 300 thương hiệu xa xỉ toàn cầu' },
      { icon: 'Trees', title: 'Công Viên Xanh 13ha', desc: 'Đường chạy bộ ven sông và quảng trường ánh sáng' },
      { icon: 'Shield', title: 'Hệ Thống An Ninh AI', desc: 'Nhận diện khuôn mặt và camera giám sát 360 độ toàn khu' },
    ],
    masterplanImg: 'https://images.unsplash.com/photo-1524813686514-a57563d77d61?auto=format&fit=crop&w=1200&q=80',
    units: [
      { type: 'Nhà phố SOHO 1LK', area: '95 m²', price: '38 Tỷ', bedrooms: '4 PN', bathrooms: '5 WC', status: 'Đang mở bán' },
      { type: 'Căn hộ Masteri Park 2PN', area: '75 m²', price: '8.5 Tỷ', bedrooms: '2 PN', bathrooms: '2 WC', status: 'Sắp ra mắt' },
      { type: 'Căn hộ Masteri Park 3PN', area: '105 m²', price: '12.8 Tỷ', bedrooms: '3 PN', bathrooms: '3 WC', status: 'Sắp ra mắt' },
      { type: 'Shophouse Kênh Đào', area: '140 m²', price: '65 Tỷ', bedrooms: '5 PN', bathrooms: '6 WC', status: 'Giỏ hàng độc quyền' },
    ],
    handoverDate: 'Quý 4/2026',
    legal: 'Sở hữu lâu dài (Người Việt Nam) / 50 năm (Người nước ngoài)',
  },
  {
    id: 202,
    title: 'Heritage West Lake Tây Hồ',
    slug: 'heritage-west-lake-tay-ho',
    developer: 'CapitaLand Development',
    location: '677 Lạc Long Quân, Phường Phú Thượng, Quận Tây Hồ, Hà Nội',
    district: 'Tây Hồ',
    city: 'Hà Nội',
    priceRange: 'Từ 140 - 220 triệu/m²',
    priceNum: 140,
    scale: '173 Căn hộ hạng sang siêu VIP ôm trọn Hồ Tây',
    status: 'Đang mở bán',
    type: 'Khu phức hợp Căn hộ & Shophouse',
    thumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    ],
    overview: 'Kiệt tác căn hộ chuẩn 6 sao độc nhất bên bờ Hồ Tây của tập đoàn CapitaLand, trang bị thang máy riêng cho từng căn hộ và bể bơi nước nóng trên tầng mái.',
    amenities: [
      { icon: 'Waves', title: 'Bể Bơi Vô Cực Nước Nóng Tầng Mái', desc: 'Bể bơi nước nóng bốn mùa view ngắm trọn vẹn 500ha mặt nước Hồ Tây' },
      { icon: 'Shield', title: 'Thang Máy Riêng Từng Căn Hộ', desc: 'Đảm bảo sự riêng tư và đẳng cấp tối thượng cho chủ nhân' },
      { icon: 'Sparkles', title: 'Dịch Vụ Quản Gia The Ascott', desc: 'Vận hành theo tiêu chuẩn khách sạn 6 sao quốc tế' },
    ],
    masterplanImg: 'https://images.unsplash.com/photo-1524813686514-a57563d77d61?auto=format&fit=crop&w=1200&q=80',
    units: [
      { type: 'Căn hộ 2 Phòng Ngủ', area: '94 m²', price: '14.5 Tỷ', bedrooms: '2 PN', bathrooms: '2 WC', status: 'Còn 4 căn' },
      { type: 'Căn hộ 3 Phòng Ngủ', area: '145 m²', price: '22.8 Tỷ', bedrooms: '3 PN', bathrooms: '3 WC', status: 'Đang mở bán' },
      { type: 'Penthouse Duplex Hồ Tây', area: '320 m²', price: '68 Tỷ', bedrooms: '4 PN', bathrooms: '5 WC', status: 'Độc quyền 2 căn' },
    ],
    handoverDate: 'Đã cất nóc - Bàn giao 2026',
    legal: 'Sổ hồng sở hữu lâu dài',
  },
  {
    id: 203,
    title: 'Vinhomes Grand Park Quận 9',
    slug: 'vinhomes-grand-park-quan-9',
    developer: 'Vingroup',
    location: 'Đường Nguyễn Xiển & Phước Thiện, Phường Long Thạnh Mỹ, TP. Thủ Đức, TP.HCM',
    district: 'Quận 2 (TP. Thủ Đức)',
    city: 'TP. Hồ Chí Minh',
    priceRange: 'Từ 45 - 90 triệu/m²',
    priceNum: 45,
    scale: '271 ha - Đại đô thị thông minh đẳng cấp số 1 miền Nam',
    status: 'Đang mở bán',
    type: 'Khu đô thị sinh thái',
    thumbnail: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    overview: 'Đại đô thị sinh thái đẳng cấp với đại công viên 36ha quy mô hàng đầu Đông Nam Á, hệ sinh thái Vingroup trọn vẹn: Vinschool, Vinmec, Vincom Mega Mall, VinBus.',
    amenities: [
      { icon: 'Trees', title: 'Đại Công Viên 36ha', desc: '15 công viên chủ đề đa dạng bao gồm biển hồ cát trắng' },
      { icon: 'Building2', title: 'TTTM Vincom Mega Mall', desc: 'TTTM lớn nhất hệ thống miền Nam chuẩn Life-Design Mall' },
      { icon: 'GraduationCap', title: 'Hệ Thống Vinschool', desc: 'Từ mầm non đến THPT chuẩn Cambridge quốc tế' },
    ],
    masterplanImg: 'https://images.unsplash.com/photo-1524813686514-a57563d77d61?auto=format&fit=crop&w=1200&q=80',
    units: [
      { type: 'Căn hộ Studio The Beverly', area: '35 m²', price: '2.1 Tỷ', bedrooms: '1 PN', bathrooms: '1 WC', status: 'Bàn giao ngay' },
      { type: 'Căn hộ 2PN The Origami', area: '68 m²', price: '3.4 Tỷ', bedrooms: '2 PN', bathrooms: '2 WC', status: 'Bàn giao ngay' },
      { type: 'Căn hộ 3PN Glory Heights', area: '92 m²', price: '4.9 Tỷ', bedrooms: '3 PN', bathrooms: '2 WC', status: 'Đang mở bán' },
    ],
    handoverDate: 'Đã bàn giao từng phần',
    legal: 'Sổ hồng sở hữu lâu dài',
  },
  {
    id: 204,
    title: 'Ecopark Hưng Yên Grand The Island',
    slug: 'ecopark-hung-yen-grand-the-island',
    developer: 'Ecopark Corporation',
    location: 'Khu đô thị Ecopark, Văn Giang, Hưng Yên (Cạnh Hà Nội)',
    district: 'Gia Lâm',
    city: 'Hà Nội',
    priceRange: 'Từ 80 - 160 triệu/m²',
    priceNum: 80,
    scale: '500 ha - Thành phố triệu cây xanh lớn nhất Việt Nam',
    status: 'Đang mở bán',
    type: 'Biệt thự Đảo siêu sang',
    thumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    overview: 'Quần thể biệt thự đảo thượng lưu vươn mình giữa mặt nước xanh ngọc bích, sở hữu mật độ 120 cây xanh/người, mang lại chuẩn sống chữa lành tinh khiết.',
    amenities: [
      { icon: 'Trees', title: '1 Triệu Cây Xanh Cổ Thụ', desc: 'Không khí trong lành mát mẻ hơn nội đô từ 2-4 độ C' },
      { icon: 'Shield', title: 'Du Thuyền Đưa Đón Riêng', desc: 'Dịch vụ đưa đón cư dân biệt thự đảo bằng du thuyền cao cấp' },
      { icon: 'Award', title: 'Sân Golf 18 Hố', desc: 'Học viện golf EPGA đẳng cấp thế giới' },
    ],
    masterplanImg: 'https://images.unsplash.com/photo-1524813686514-a57563d77d61?auto=format&fit=crop&w=1200&q=80',
    units: [
      { type: 'Biệt thự Đảo Jade', area: '260 m²', price: '32 Tỷ', bedrooms: '4 PN', bathrooms: '5 WC', status: 'Đang mở bán' },
      { type: 'Biệt thự Đảo Sapphire', area: '380 m²', price: '52 Tỷ', bedrooms: '5 PN', bathrooms: '6 WC', status: 'Đang mở bán' },
    ],
    handoverDate: 'Quý 2/2026',
    legal: 'Sổ đỏ sở hữu lâu dài',
  },
];

export const PORTAL_NEWS: PortalNews[] = [
  {
    id: 301,
    title: 'Luật Đất đai mới có hiệu lực: Tác động gì đến giá bất động sản và quyền lợi người mua?',
    slug: 'luat-dat-dai-moi-tac-dong-gia-bat-dong-san',
    category: 'Pháp lý & Quy hoạch',
    date: '28/08/2026',
    author: 'PlatformBDS Research Team',
    img: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    summary: 'Phân tích chi tiết các điểm mới trong việc bỏ khung giá đất, cấp sổ đỏ cho đất không giấy tờ trước 2014 và quy định thanh toán tiền thuê đất một lần.',
    content: 'Luật Đất đai (sửa đổi) chính thức có hiệu lực tạo nên bước ngoặt lớn cho toàn bộ thị trường bất động sản Việt Nam.',
    views: 3420,
    tags: ['Luật đất đai', 'Sổ đỏ', 'Pháp lý BĐS', 'Quy hoạch'],
  },
  {
    id: 302,
    title: 'Top 5 khu vực bất động sản TP.HCM có tỷ suất sinh lời cho thuê cao nhất năm 2026',
    slug: 'top-5-khu-vuc-bds-tphcm-sinh-loi-cho-thue-cao-nhat',
    category: 'Kinh nghiệm đầu tư',
    date: '26/08/2026',
    author: 'Nguyễn Văn Minh - Chuyên gia BĐS',
    img: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&w=800&q=80',
    summary: 'Báo cáo độc quyền về tỷ suất cho thuê căn hộ và shophouse tại khu Đông TP. Thủ Đức, khu Nam Quận 7 và khu Tây Bình Tân.',
    content: 'Khảo sát từ dữ liệu thực tế hơn 25.000 tin đăng tại PlatformBDS cho thấy thị trường cho thuê căn hộ TP.HCM đang hồi phục mạnh mẽ với tỷ suất lợi nhuận trung bình từ 4.8% đến 6.2%/năm.',
    views: 2890,
    tags: ['Đầu tư BĐS', 'Thuê nhà', 'Thủ Đức', 'Phú Mỹ Hưng'],
  },
  {
    id: 303,
    title: 'Cách xem hướng nhà hợp phong thủy rước tài lộc cho gia chủ theo từng cung mệnh',
    slug: 'cach-xem-huong-nha-hop-phong-thuy-ruoc-tai-loc',
    category: 'Phong thủy nhà đất',
    date: '22/08/2026',
    author: 'Chuyên gia Phong Thủy Hải Nam',
    img: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    summary: 'Hướng dẫn chuẩn xác cách tính quái số, xác định nhóm Đông Tứ Trạch và Tây Tứ Trạch khi chọn mua nhà đất hoặc căn hộ chung cư.',
    content: 'Trong phong thủy Bất Động Sản, việc chọn đúng hướng nhà mang lại vượng khí, tài lộc và sức khỏe dồi dào cho gia chủ.',
    views: 4150,
    tags: ['Phong thủy', 'Hướng nhà', 'Đông Tứ Trạch', 'Căn hộ chung cư'],
  },
  {
    id: 304,
    title: 'Cẩm nang thuê căn hộ chung cư Hà Nội: 7 điều cần kiểm tra kỹ trước khi đặt cọc',
    slug: 'cam-nang-thue-can-ho-chung-cu-ha-noi',
    category: 'Cẩm nang mua bán',
    date: '20/08/2026',
    author: 'Phạm Hoàng Anh',
    img: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
    summary: 'Kinh nghiệm đắt giá từ chuyên viên BĐS giúp bạn tránh bẫy chi phí phát sinh khi thuê nhà tại các quận Cầu Giấy, Nam Từ Liêm, Tây Hồ.',
    content: 'Khi thuê căn hộ chung cư tại Hà Nội, việc nắm rõ biểu phí quản lý, phí gửi xe và tình trạng trang thiết bị nội thất sẽ giúp bạn tiết kiệm hàng chục triệu đồng mỗi năm.',
    views: 2650,
    tags: ['Thuê chung cư Hà Nội', 'Cẩm nang thuê nhà', 'Đặt cọc'],
  },
];
`;

fs.writeFileSync(PORTAL_DATA_PATH, newPortalDataContent, 'utf-8');
console.log('✅ Đã cập nhật thành công portalData.ts với dữ liệu BĐS phong phú!');
